### ISSUE TITLE
ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by TONG369** [j96w/DenseFusion#124]
Hello! I'm a student who just got in touch with deep learning. 
Operating Environment：Ubuntu16.04 64bit  python3.5  cuda8.0  pytorch0.4.1 GeForce GTX 1080 Ti
Now I need to ask you a question.I download the linemod_preprocessed dataset from https://drive.google.com/drive/folders/19ivhpakm9dor12fzc8idfczwrpfxho7 and put it under the datasets / linmod folder. When I run  this comand:sh ./experiments/scripts/train_linemod.sh.I find the following error: 
yangchengwu@robotvision-PowerEdge-T630:/home/dl/yangchengwu/Downloads/DenseFusion$ sh ./experiments/scripts/train_linemod.sh
+ set -e
+ export PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ python3 ./tools/train.py --dataset linemod --dataset_root ./datasets/linemod/Linemod_preprocessed
/home/dl/yangchengwu/Downloads/DenseFusion/lib/transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
Object 1 buffer loaded
Object 2 buffer loaded
Object 4 buffer loaded
Object 5 buffer loaded
Object 6 buffer loaded
Object 8 buffer loaded
Object 9 buffer loaded
Object 10 buffer loaded
Object 11 buffer loaded
Object 12 buffer loaded
Object 13 buffer loaded
Object 14 buffer loaded
Object 15 buffer loaded
Object 1 buffer loaded
Object 2 buffer loaded
Object 4 buffer loaded
Object 5 buffer loaded
Object 6 buffer loaded
Object 8 buffer loaded
Object 9 buffer loaded
Object 10 buffer loaded
Object 11 buffer loaded
Object 12 buffer loaded
Object 13 buffer loaded
Object 14 buffer loaded
Object 15 buffer loaded
>>>>>>>>----------Dataset loaded!---------<<<<<<<<
length of the training set: 2373
length of the testing set: 1336
number of sample points on mesh: 500
symmetry object list: [7, 8]
/home/dl/yangchengwu/.local/lib/python3.5/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
2019-11-14 18:34:56,083 : Train time 00h 00m 00s, Training started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
  File "/usr/lib/python3.5/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range
This value error is all the time until I press ctrl+c. Please tell me what caused the following problems ?What should I do to solve this problem?I am looking forward to your reply. Thankyou very much!!!

**Comment by TONG369** [comment]
I've solved this problem by myself. I'm sorry to cause you any trouble
