### ISSUE TITLE
about info.yml and models_info.yml 

### ISSUE THREAD

**Issue by GaoHuaZhang** [j96w/DenseFusion#191]
Can someone tell me how to generate info.yml and models_info.yml ！I'm stuck here～

**Comment by ame5r** [comment]
found something?

**Comment by Ultraopxt** [comment]
> Can someone tell me how to generate info.yml and models_info.yml ！I'm stuck here～

Me too,

Have you got the idea?

Thanks

**Comment by JayLuoShui** [comment]
> > Can someone tell me how to generate info.yml and models_info.yml ！I'm stuck here～
> 
> Me too,
> 
> Have you got the idea?
> 
> Thanks

兄弟，这个你最终搞定了吗

**Comment by JayLuoShui** [comment]
> Can someone tell me how to generate info.yml and models_info.yml ！I'm stuck here～
球球了，帮帮孩子

**Comment by GaoHuaZhang** [comment]
i think you can try the [bop_toolkit](https://github.com/thodan/bop_toolkit) ,there is many useful tools to dealwith such problem

**Comment by JayLuoShui** [comment]
> i think you can try the [bop_toolkit](https://github.com/thodan/bop_toolkit) ,there is many useful tools to dealwith such problem

谢谢铁子的回复，我试过bop_toolkit 可以求出models_info.yml,但gt.yml我今天还没搞定，不知道是不是scene_camera.json这个文件我搞的不对还是怎么的，一直这样
Traceback (most recent call last):
  File "/home/wei/Code/bop_toolkit/scripts/calc_gt_info.py", line 88, in <module>
    dp_split['scene_camera_tpath'].format(scene_id=scene_id))
  File "/home/wei/Code/bop_toolkit/bop_toolkit_lib/inout.py", line 151, in load_scene_camera
    if 'cam_K' in scene_camera[im_id].keys():
AttributeError: 'list' object has no attribute 'keys'

我的scene_camera.json文件里面是这样的
{
 "cam_K":[384.3522644042969, 0.0, 325.4162292480469, 0.0, 383.8063659667969, 244.2845458984375, 0.0, 0.0, 1.0],
 "depth_scale": 1.0
}
我没找到对应的文件模板来改，希望等到你的帮助 。

**Comment by GaoHuaZhang** [comment]
> > i think you can try the [bop_toolkit](https://github.com/thodan/bop_toolkit) ,there is many useful tools to dealwith such problem
> 
> 谢谢铁子的回复，我试过bop_toolkit 可以求出models_info.yml,但gt.yml我今天还没搞定，不知道是不是scene_camera.json这个文件我搞的不对还是怎么的，一直这样 Traceback (most recent call last): File "/home/wei/Code/bop_toolkit/scripts/calc_gt_info.py", line 88, in dp_split['scene_camera_tpath'].format(scene_id=scene_id)) File "/home/wei/Code/bop_toolkit/bop_toolkit_lib/inout.py", line 151, in load_scene_camera if 'cam_K' in scene_camera[im_id].keys(): AttributeError: 'list' object has no attribute 'keys'
> 
> 我的scene_camera.json文件里面是这样的 { "cam_K":[384.3522644042969, 0.0, 325.4162292480469, 0.0, 383.8063659667969, 244.2845458984375, 0.0, 0.0, 1.0], "depth_scale": 1.0 } 我没找到对应的文件模板来改，希望等到你的帮助 。

scenecamera.json是有问题。你可以去bop官网下个官方数据集参考下，你这个文件脚本读进去是个列表，原本应该是个字典

**Comment by JayLuoShui** [comment]
> > > i think you can try the [bop_toolkit](https://github.com/thodan/bop_toolkit) ,there is many useful tools to dealwith such problem
> > 
> > 
> > 谢谢铁子的回复，我试过bop_toolkit 可以求出models_info.yml,但gt.yml我今天还没搞定，不知道是不是scene_camera.json这个文件我搞的不对还是怎么的，一直这样 Traceback (most recent call last): File "/home/wei/Code/bop_toolkit/scripts/calc_gt_info.py", line 88, in dp_split['scene_camera_tpath'].format(scene_id=scene_id)) File "/home/wei/Code/bop_toolkit/bop_toolkit_lib/inout.py", line 151, in load_scene_camera if 'cam_K' in scene_camera[im_id].keys(): AttributeError: 'list' object has no attribute 'keys'
> > 我的scene_camera.json文件里面是这样的 { "cam_K":[384.3522644042969, 0.0, 325.4162292480469, 0.0, 383.8063659667969, 244.2845458984375, 0.0, 0.0, 1.0], "depth_scale": 1.0 } 我没找到对应的文件模板来改，希望等到你的帮助 。
> 
> scenecamera.json是有问题。你可以去bop官网下个官方数据集参考下，你这个文件脚本读进去是个列表，原本应该是个字典

哈哈，这几天一直在忙着搞这个，铁子说的方法是正确的可行的有建设性的，但还是出了小问题，还在解决中
