### ISSUE TITLE
undefined symbol:_Py_Dealloc

### ISSUE THREAD

**Issue by sunshantong** [j96w/DenseFusion#2]
When trying to run the training script ./train_ycb.sh on Ubuntu with Python2.7.12, it fails with the stack trace:

+ set -e
+ export PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ python ./tools/train.py --dataset ycb --dataset_root ./data/YCB_Video_Dataset
/home/user/Work/DenseFusion/lib/transformations.py:1912: UserWarning: failed to import module _transformations
  warnings.warn('failed to import module %s' % name)
Traceback (most recent call last):
  File "./tools/train.py", line 26, in <module>
    from lib.loss import Loss
  File "/home/user/Work/DenseFusion/lib/loss.py", line 9, in <module>
    from lib.knn.__init__ import KNearestNeighbor
  File "/home/user/Work/DenseFusion/lib/knn/__init__.py", line 7, in <module>
    from lib.knn import knn_pytorch as knn_pytorch
  File "/home/user/Work/DenseFusion/lib/knn/knn_pytorch/__init__.py", line 3, in <module>
    from ._knn_pytorch import lib as _lib, ffi as _ffi
ImportError: /home/user/Work/DenseFusion/lib/knn/knn_pytorch/_knn_pytorch.so: undefined symbol: _Py_Dealloc

I want to addressed via building _knn_pytorch.so with [Py2,](https://github.com/pantsbuild/pants/issues/6985) but it still fails with the stack trace:

python2 build_ffi.py
Traceback (most recent call last):
  File "build_ffi.py", line 19, in <module>
    include_dirs=[osp.join(abs_path, 'include')]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 176, in create_extension
    ffi = cffi.FFI()
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 46, in __init__
    import _cffi_backend as backend
ImportError: /usr/local/lib/python2.7/dist-packages/_cffi_backend.so: undefined symbol: PyUnicodeUCS2_FromUnicode
Makefile:31: recipe for target 'build/knn_pytorch/_knn_pytorch.so' failed
make: *** [build/knn_pytorch/_knn_pytorch.so] Error 1

**Comment by j96w** [comment]
Make sure you are building with the correct version of PyTorch(0.4.1).

**Comment by j96w** [comment]
The _knn_pytorch.so in this repo is built with python3. If you want to use python2, you need to rebuild the lib/knn (with PyTorch-0.4.1).
For your case, please make sure your CFFI is correctly installed. More information https://cffi.readthedocs.io/en/latest/installation.html#linux-and-os-x-ucs2-versus-ucs4.

**Comment by sunshantong** [comment]
> The _knn_pytorch.so in this repo is built with python3. If you want to use python2, you need to rebuild the lib/knn (with PyTorch-0.4.1).
> For your case, please make sure your CFFI is correctly installed. More information https://cffi.readthedocs.io/en/latest/installation.html#linux-and-os-x-ucs2-versus-ucs4.

figure it out, thank you for helping me !

**Comment by hamza-04** [comment]
hi @j96w , i'm working on conda 2.7 , so i built the knn_torch with python 2 in conda environment and always get this problem with modules , 
 
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python ./tools/train.py --dataset linemod --dataset_root ./datasets/linemod/Linemod_preprocessed
Traceback (most recent call last):
  File "./tools/train.py", line 12, in <module>
    import numpy as np
ImportError: No module named numpy

i tried it also outside cud a environment , always the same probleme . i don't know if i miss something !
thank you in advance

**Comment by j96w** [comment]
@hamza-04 's problem has been solved in [Issue#17](https://github.com/j96w/DenseFusion/issues/17).
