### ISSUE TITLE
有没有支持PyTorch1.5的版本？

### ISSUE THREAD

**Issue by zhanghaobucunzai** [j96w/DenseFusion#200]

**Comment by kuaitoukid** [comment]
You may refer this https://github.com/kuaitoukid/DenseFusion, I replace the KNN with a pytorch version, but sacrificed the speed.

**Comment by wangqingyu985** [comment]
> 

I used your repo and encountered this problem

Traceback (most recent call last):
  File "/home/wangqingyu/桌面/DenseFusion/tools/train.py", line 26, in <module>
    from lib.loss import Loss
  File "/home/wangqingyu/桌面/DenseFusion/lib/loss.py", line 9, in <module>
    from lib.knn.__init__ import KNearestNeighbor
  File "/home/wangqingyu/桌面/DenseFusion/lib/knn/__init__.py", line 7, in <module>
    from lib.knn import knn_pytorch as knn_pytorch
  File "/home/wangqingyu/桌面/DenseFusion/lib/knn/knn_pytorch/__init__.py", line 1, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/wangqingyu/anaconda3/envs/new/lib/python3.8/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by explore-code-world7** [comment]
> No description provided.

if don't mind, you can see [my repo](https://github.com/explore-code-world7/DenseFusion-For-torch-1.0)
