### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by AbdulrahmanAlsumeri** [j96w/DenseFusion#214]
After running the script 
./experiments/scripts/eval_linemod.sh

The following error shows up
No.7190 Pass! Distance: 0.008826363647664644
No.7191 NOT Pass! Distance: 0.030700618748845932
No.7192 Pass! Distance: 0.009671199228185249
Traceback (most recent call last):
  File "./tools/eval_linemod.py", line 126, in <module>
    inds = KNearestNeighbor.apply(target.unsqueeze(0), pred.unsqueeze(0))
  File "/home/abdulrahman/Downloads/DenseFusion-Pytorch-1.0/lib/knn/__init__.py", line 20, in forward
    knn_pytorch.knn(ref, query, inds).cuda()
RuntimeError: Not compiled with GPU support

![error](https://user-images.githubusercontent.com/101629669/205440606-b71cf268-f876-45c1-9f11-8550a5f6159c.png)

Although i doubled check if cuda is installed with pytorch and it is actually installed using the following line of code:

torch.cuda.is_available() and shows True

**Comment by Harrydsk** [comment]
did u solve the problem my friend
