### ISSUE TITLE
Training vanilla SegNet

### ISSUE THREAD

**Issue by BarbeBleue** [j96w/DenseFusion#36]
When I try to run  
'python3 train.py --dataset_root=./datasets/ycb/YCB_Video_Dataset'

I got the following issue :
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    for i, data in enumerate(dataloader, 0):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/intern/disk2/DenseFusion/vanilla_segmentation/data_controller.py", line 47, in __getitem__
    label = np.array(Image.open('{0}/{1}-label.png'.format(self.root, self.path[index])))
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './datasets/ycb/YCB_Video_Dataset/data_syn/002715-label.png'

I tried several times and got the same issue with different #-label.png files and the files are in the folder so I don't really understand the error. It is always the 22nd call that crash. Any idea ?
Thanks

**Comment by BarbeBleue** [comment]
Well what happend is that I did a copy-paste but there is a mistake in the root dir in the command line. 
It should be:
`python3 train.py --dataset_root=../datasets/ycb/YCB_Video_Dataset`
