### ISSUE TITLE
ImportError : torch.utils.ffi requires the cffi pacakge

### ISSUE THREAD

**Issue by MyungHaSong** [j96w/DenseFusion#42]
Hi 
when trying to run the training script experiments/scripts/train_ycb.sh on ubuntu with python2.7.12,
it fails with the stack trace:

set -e
export PYTHONUNBUFFERED=True
EXPORT CUDA_VISIBLE_DEVICES=0
python2 ./tools/train.py --dataset ycb --dataset_root ./datasets/ycb/YCB_VIdeoDataset
/root/catkin_ws/densefusion/DenseFusion/lib/transformations.py:1912: UserWarning: failed to import module _transformations

warnings.warn('failed to import module %s' % name)

Traceback (most recent call last):
  File "./tools/train.py", line 26, in <module>
    from lib.loss import Loss
  File "/root/catkin_ws/densefusion/DenseFusion/lib/loss.py", line 9, in <module>
    from lib.knn.__init__ import KNearestNeighbor
  File "/root/catkin_ws/densefusion/DenseFusion/lib/knn/__init__.py", line 7, in <module>
    from lib.knn import knn_pytorch as knn_pytorch
  File "/root/catkin_ws/densefusion/DenseFusion/lib/knn/knn_pytorch/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 14, in <module>
    raise ImportError("torch.utils.ffi requires the cffi package")

ImportError: torch.utils.ffi requires the cffi package

I access DenseFusion/lib/knn folder and revised Makefile PYTHON:= python2
I run $make

python2 build_ffi.py
Traceback (most recent call last):
  File "build_ffi.py", line 5, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 14, in <module>
    raise ImportError("torch.utils.ffi requires the cffi package")
ImportError: torch.utils.ffi requires the cffi package
Makefile:31: recipe for target 'build/knn_pytorch/_knn_pytorch.so' failed
make: *** [build/knn_pytorch/_knn_pytorch.so] Error 1

**Comment by j96w** [comment]
Please refer to [Issue#2](https://github.com/j96w/DenseFusion/issues/2).
