### ISSUE TITLE
runtimewarning while runing eval_ycb.py

### ISSUE THREAD

**Issue by kaixin-bai** [j96w/DenseFusion#66]
Does anybody have the same problem? For some frames it just didn't work. I'm considering whether the data i have download is correct.

Finish No.2 keyframe
Finish No.3 keyframe
Finish No.4 keyframe
Finish No.5 keyframe
Finish No.6 keyframe
Finish No.7 keyframe
Finish No.8 keyframe
Finish No.9 keyframe
Finish No.10 keyframe
Finish No.11 keyframe
Finish No.12 keyframe
Finish No.13 keyframe
Finish No.14 keyframe
Finish No.15 keyframe
Finish No.16 keyframe
Finish No.17 keyframe
Finish No.18 keyframe
Finish No.19 keyframe
Finish No.20 keyframe
Finish No.21 keyframe
Finish No.22 keyframe
Finish No.23 keyframe
Finish No.24 keyframe
Finish No.25 keyframe
/home/xxx/.local/lib/python3.6/site-packages/numpy/lib/arraypad.py:1346: `RuntimeWarning: divide by zero encountered in long_scalars  safe_pad * (pad_before // safe_pad))`

**Comment by intrepidChw** [comment]
I have encountered the same problem. Have you solved it?

**Comment by intrepidChw** [comment]
Hi, I solved the problem by changing the numpy version from 1.16 to 1.11.3

**Comment by kaixin-bai** [comment]
> Hi, I solved the problem by changing the numpy version from 1.16 to 1.11.3

HI, intrepidChw. If i changed the version of numpy from 1.16 to 1.11.3, i got some new error below, seems that scipy cannot work with numpy with lower version.

RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "/data/hdd1/kb/agile/bkx_master/6dofbkx/tools/eval_ycb_6dof.py", line 11, in <module>
    import scipy.io as scio
  File "/home/kb/.local/lib/python3.6/site-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/home/kb/.local/lib/python3.6/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/home/kb/.local/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 11, in <module>
    from .mio4 import MatFile4Reader, MatFile4Writer
  File "/home/kb/.local/lib/python3.6/site-packages/scipy/io/matlab/mio4.py", line 11, in <module>
    import scipy.sparse
  File "/home/kb/.local/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 230, in <module>
    from .csr import *
  File "/home/kb/.local/lib/python3.6/site-packages/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import

**Comment by kaixin-bai** [comment]
just found that numpy with version 1.13.3 works fine.

**Comment by kaixin-bai** [comment]
[https://github.com/j96w/DenseFusion/issues/15](url)

**Comment by andrewqho** [comment]
How did you change the numpy version? I tried pip install --upgrade numpy==1.13.3, but I ran into a slew of errors.

**Comment by kaixin-bai** [comment]
> How did you change the numpy version? I tried pip install --upgrade numpy==1.13.3, but I ran into a slew of errors.

maybe you can try first uninstall the numpy with "pip uninstall numpy" or "conda uninstall numpy" if you are using a conda environment, and then reinstall the numpy with version 1.13.3 with "conda install numpy=1.13.3". Good luck!

**Comment by akeaveny** [comment]
Hi @kaixin-bai , @j96w, 

I keep getting this error but I'm not able to downgrade from numpy 1.18 to 1.13 with Cuda 10.2. Any recommendations? My dataset has images that are 720 x 1280.

`Traceback (most recent call last):
  File "./tools/train_pringles.py", line 267, in <module>
    main()
  File "./tools/train_pringles.py", line 144, in main
    for i, data in enumerate(dataloader, 0):
  File "/home/akeaveny/anaconda3/envs/object-rpe/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 623, in __next__
    return self._process_next_batch(batch)
  File "/home/akeaveny/anaconda3/envs/object-rpe/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ZeroDivisionError: Traceback (most recent call last):
  File "/home/akeaveny/anaconda3/envs/object-rpe/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/akeaveny/anaconda3/envs/object-rpe/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/akeaveny/catkin_ws/src/object-rpe-ak/DenseFusion/datasets/pringles/dataset_pringles.py", line 193, in __getitem__
    choose = np.pad(choose, (0, self.num_pt - len(choose)), 'wrap')
  File "/home/akeaveny/anaconda3/envs/object-rpe/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 1375, in pad
    safe_pad * (pad_before // safe_pad))
ZeroDivisionError: integer division or modulo by zero
`
