### ISSUE TITLE
RuntimeError: the derivative for 'index' is not implemented

### ISSUE THREAD

**Issue by jarygrace** [j96w/DenseFusion#80]

**Comment by jarygrace** [comment]
When I run the eval_linemod.sh to train DenseFusion on LineMod dataset. It occured to have this problem after saved the best test model.
2019-08-27 20:40:32,662 : Test time 09h 53m 34s Test Frame No.1326 dis:0.011307657696306705
2019-08-27 20:40:32,672 : Test time 09h 53m 34s Test Frame No.1327 dis:0.010947037488222122
2019-08-27 20:40:32,683 : Test time 09h 53m 34s Test Frame No.1328 dis:0.00586977694183588
2019-08-27 20:40:32,695 : Test time 09h 53m 34s Test Frame No.1329 dis:0.010964779183268547
2019-08-27 20:40:32,704 : Test time 09h 53m 34s Test Frame No.1330 dis:0.0037663683760911226
2019-08-27 20:40:32,714 : Test time 09h 53m 34s Test Frame No.1331 dis:0.019830429926514626
2019-08-27 20:40:32,724 : Test time 09h 53m 34s Test Frame No.1332 dis:0.018335606902837753
2019-08-27 20:40:32,735 : Test time 09h 53m 34s Test Frame No.1333 dis:0.0059200795367360115
2019-08-27 20:40:32,745 : Test time 09h 53m 34s Test Frame No.1334 dis:0.015959134325385094
2019-08-27 20:40:32,756 : Test time 09h 53m 34s Test Frame No.1335 dis:0.009483909234404564
2019-08-27 20:40:32,829 : Test time 09h 53m 34s Epoch 19 TEST FINISH Avg dis: 0.01285627536976436
19 >>>>>>>>----------BEST TEST MODEL SAVED---------<<<<<<<<
Object 1 buffer loaded
Object 2 buffer loaded
Object 4 buffer loaded
Object 5 buffer loaded
Object 6 buffer loaded
Object 8 buffer loaded
Object 9 buffer loaded
Object 10 buffer loaded
Object 11 buffer loaded
Object 12 buffer loaded
Object 13 buffer loaded
Object 14 buffer loaded
Object 15 buffer loaded
Object 1 buffer loaded
Object 2 buffer loaded
Object 4 buffer loaded
Object 5 buffer loaded
Object 6 buffer loaded
Object 8 buffer loaded
Object 9 buffer loaded
Object 10 buffer loaded
Object 11 buffer loaded
Object 12 buffer loaded
Object 13 buffer loaded
Object 14 buffer loaded
Object 15 buffer loaded
>>>>>>>>----------Dataset loaded!---------<<<<<<<<
length of the training set: 2373
length of the testing set: 1336
number of sample points on mesh: 500
symmetry object list: [7, 8]
2019-08-27 20:42:05,224 : Train time 09h 55m 07s, Training started
Traceback (most recent call last):
  File "./tools/train.py", line 237, in <module>
    main()
  File "./tools/train.py", line 145, in main
    dis, new_points, new_target = criterion_refine(pred_r, pred_t, new_target, model_points, idx, new_points)
  File "/home/srt/anaconda3/envs/DenseFusion/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/srt/Project/DenseFusion-Pytorch-1.0/lib/loss_refiner.py", line 76, in forward
    return loss_calculation(pred_r, pred_t, target, model_points, idx, points, self.num_pt_mesh, self.sym_list)
  File "/home/srt/Project/DenseFusion-Pytorch-1.0/lib/loss_refiner.py", line 45, in loss_calculation
    target = torch.index_select(target, 1, inds.view(-1) - 1)
RuntimeError: the derivative for 'index' is not implemented

**Comment by j96w** [comment]
Hi, this might because your best model has reached the refinement margin and it starts to create the refinement dataloader to train the refinement model.

**Comment by jarygrace** [comment]
Thank you so much !

在 2019-09-20 02:25:38，"Chen (Jeremy) Wang" <notifications@github.com> 写道：


Closed #80.
