### ISSUE TITLE
OSError: could not read bytes

### ISSUE THREAD

**Issue by RobbyHuang** [j96w/DenseFusion#96]
When I  run the vanilla_segmentation code with the YCB Video, there is the following error "OSError: could not read bytes". 
The environment is RTX2080(8G), Ubuntu 16.04 LTS, python 1.0.0, torchvision 0.2.0

I try to search the error on Ineternet, someone said that may be cause by the damaged mat file. But I fail to find out which mat file is damaged from the error information.
Do you know how to solve this problem?
Thank you so much!

```
Traceback (most recent call last):
  File "train.py", line 69, in <module>
    for i, data in enumerate(dataloader, 0):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/workshop/user_data/Robby/DenseFusion-master/vanilla_segmentation/data_controller.py", line 44, in __getitem__
    meta = scio.loadmat('{0}/{1}-meta.mat'.format(self.root, self.path[index]))
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 705, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 778, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 195, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 188, in scipy.io.matlab.streams.ZlibInputStream.read_into
OSError: could not read bytes
```

**Comment by j96w** [comment]
Hi, I think the mat file is not broken since it works fine on my side. Maybe you can print some information in the data loader? Then probably you can figure out which mat is broken? Not very sure what's the problem.

**Comment by RobbyHuang** [comment]
Hi, Thanks for your reply!
I use `meta = scio.loadmat('{0}/{1}-meta.mat'.format(root,fpath))` to read all the mat files of the Datasets, and find that there are three mat file can't be read. And I used Matlab to open these mat file,  I also got an error that the file can't be read. So I think that  the errors were cause by the damaged mat file. And the dataset I use is download from [https://github.com/yuxng/PoseCNN/issues/81#issuecomment-455029641](url) but not from the official link, I can't download from the google drive.  I guess that the dataset that I  downloaded is 
broken. 
Finally  I replace the damage mat file and other files with the same number with the previous files.

**Comment by j96w** [comment]
I see. Thanks for mention this problem and your hard work.

**Comment by PatrickFeng** [comment]
> Hi, Thanks for your reply! I use `meta = scio.loadmat('{0}/{1}-meta.mat'.format(root,fpath))` to read all the mat files of the Datasets, and find that there are three mat file can't be read. And I used Matlab to open these mat file, I also got an error that the file can't be read. So I think that the errors were cause by the damaged mat file. And the dataset I use is download from [https://github.com/yuxng/PoseCNN/issues/81#issuecomment-455029641](url) but not from the official link, I can't download from the google drive. I guess that the dataset is broken. Finally I replace the damage mat file and other files with the same number with the previous files.

Hi, I met the same issue. The only way I have to download the YCB-Video dataset is the BaiduDisk link. It tough to download the dataset from Google Drive in China mainland. Could you share the unbroken files? Much appreciated.

**Comment by PatrickFeng** [comment]
> > Hi, Thanks for your reply! I use `meta = scio.loadmat('{0}/{1}-meta.mat'.format(root,fpath))` to read all the mat files of the Datasets, and find that there are three mat file can't be read. And I used Matlab to open these mat file, I also got an error that the file can't be read. So I think that the errors were cause by the damaged mat file. And the dataset I use is download from [https://github.com/yuxng/PoseCNN/issues/81#issuecomment-455029641](url) but not from the official link, I can't download from the google drive. I guess that the dataset is broken. Finally I replace the damage mat file and other files with the same number with the previous files.
> 
> Hi, I met the same issue. The only way I have to download the YCB-Video dataset is the BaiduDisk link. It tough to download the dataset from Google Drive in China mainland. Could you share the unbroken files? Much appreciated.

I re-download the error files. It works now.
