### ISSUE TITLE
RuntimeError: shape '[1, 1, 2600, 3]' is invalid for input of size 1500

### ISSUE THREAD

**Issue by TrinhTUHH** [j96w/DenseFusion#99]
During the training I got this error and don't know how to solve it. Could someone helps me with this? Thank you!

```
length of the training set: 54818
length of the testing set: 13706
number of sample points on mesh: 2600
symmetry object list: []
2019-10-16 19:49:20,562 : Train time 02h 40m 05s, Training started
Traceback (most recent call last):
  File "./tools/train.py", line 258, in <module>
    main()
  File "./tools/train.py", line 158, in main
    loss, dis, new_points, new_target = criterion(pred_r, pred_t, pred_c, target, model_points, idx, points, opt.w, opt.refine_start)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ros/Object_Pose_Estimation/DenseFusion/lib/loss.py", line 82, in forward
    return loss_calculation(pred_r, pred_t, pred_c, target, model_points, idx, points, w, refine, self.num_pt_mesh, self.sym_list)
  File "/home/ros/Object_Pose_Estimation/DenseFusion/lib/loss.py", line 29, in loss_calculation
    model_points = model_points.view(bs, 1, num_point_mesh, 3).repeat(1, num_p, 1, 1).view(bs * num_p, num_point_mesh, 3)
RuntimeError: shape '[1, 1, 2600, 3]' is invalid for input of size 1500
```

**Comment by TrinhTUHH** [comment]
Probably because of the number of point in mesh (`self.num_pt_mesh_large ` in dataset.py)
